### ISSUE TITLE
Line-height

### ISSUE THREAD

**Issue by ugogo** [Wisembly/tapestry#105]
`$lh--l`should be `$lh--xl`, and we should create a `$lh--l`.

Example with a text with `$fz--xl` and `lh--l` — http://cl.ly/image/0h3X0I2P3j3L

**Comment by AlexandreBroudin** [comment]
Maybe a way to go with
http://stackoverflow.com/questions/30158768/function-to-calculate-vertical-rhythm
https://github.com/modularscale/modularscale-sass

**Comment by GabrielCousin** [comment]
#oklm
