### ISSUE TITLE
Utility-classes

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#106]
- [ ] Fixed
- [x] Ellipsis
- [x] Horizontally-centered (but should only contains auto margin-right and margin-left)

**Comment by GabrielCousin** [comment]
What do you think?
- `.u-hac` for horizontal centering
- `.is-fixed` for `position: fixed;`

**Comment by ugogo** [comment]
Mrf, are they really useful?

**Comment by GabrielCousin** [comment]
Well, the purpose was to decide for an unique syntax

**Comment by AlexandreBroudin** [comment]
`.u-posf` for fixed, what `u-hac`will expend to ?

```
.u-hac {
  margin-right: auto;
  margin-left: auto;
}
```

**Comment by GabrielCousin** [comment]
@alexandrebroudin, yeah this is it. It should replace `m0a` but it is quite confusing with `margin: 0 auto;`

**Comment by GabrielCousin** [comment]
I want a class that is only centering
