### ISSUE TITLE
Radius

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#127]
Should we use 6px?

**Comment by ugogo** [comment]
``` scss
$base-radius: 3px;
$radius--l: 6px;
```

?

**Comment by GabrielCousin** [comment]
I don't think we need both of them. The last protos and updates on the UI kit seems rounder to me.

**Comment by GabrielCousin** [comment]
Christine said it should be 4px ¯_(ツ)_/¯

**Comment by ugogo** [comment]
So just update the `var` :dancer:

**Comment by AlexandreBroudin** [comment]
:poodle:
