### ISSUE TITLE
Tapestry JS not compatible with liquid-fire

### ISSUE THREAD

**Issue by nicolaschenet** [Wisembly/tapestry#149]
When I try to use **liquid-fire** and **tapestry** at the same time, it doesn't work, just throw this error: `Uncaught TypeError: injectedFactory.reopenClass is not a function`

The fact is that liquid-fire is the only way to get a working onboarding after the upgrade of ember.

The error is thrown in the **factoryFor** method, in Ember source code (https://github.com/emberjs/ember.js/blob/fe9d4eb60a5be5e75fe2ad28980d5f72112b2a43/packages/container/lib/container.js#L209) , and is located precisely here (line 229):

```
var injections = injectionsFor(container, fullName);
var factoryInjections = factoryInjectionsFor(container, fullName);
var cacheable = !areInjectionsDynamic(injections) && !areInjectionsDynamic(factoryInjections);

factoryInjections._toString = registry.makeToString(factory, fullName);

var injectedFactory = factory.extend(injections);
injectedFactory.reopenClass(factoryInjections);
```

And more precisely here => `var injectedFactory = factory.extend(injections);`

After the extend, `injectedFactory` is equal to just `function () {}`, because of tapestry dropdown. See code:

```
Function.prototype.extend = function (props) {
    var constructor = function () {};
    var prototype = constructor.prototype = new this;
    if (typeof props === "object") 
        for (var key in props) prototype[key] = props[key];
    prototype.__super__ = this.prototype;
    return constructor;
};
```

**Comment by matghaleb** [comment]
https://github.com/Wisembly/tapestry/pull/150
