### ISSUE TITLE
Dropdown | White-space and padding issue

### ISSUE THREAD

**Issue by nicolaschenet** [Wisembly/tapestry#152]
When the text is a bit long, it is broken in two lines, causing visual inconsistency.
As seen with @AlexandreBroudin, using `white-space: nowrap` fixes it.

Also, consider adding a  the same `padding-right` for active and inactive elements.

![screenshot 2015-09-30 14 52 30](https://cloud.githubusercontent.com/assets/1178002/10193393/1648e2ce-6783-11e5-806d-d34832082720.png)

**Comment by GabrielCousin** [comment]
Can't remember if you discuss/fix it yet, but IMO, it would be a great thing to set a default text-align for Dropdown-items

**Comment by ugogo** [comment]
+1

**Comment by ugogo** [comment]
Did this in Solid

```
.Dropdown-item {
  white-space: nowrap;
  line-height: $base-lh;
  text-align: left;
}
```

**Comment by GabrielCousin** [comment]
Blanco :bowling:

**Comment by AlexandreBroudin** [comment]
:+1:

**Comment by nicolaschenet** [comment]
![s7xm4](https://cloud.githubusercontent.com/assets/1178002/10396374/7ea842f8-6ea2-11e5-8345-c286cfff98d9.jpg)
