### ISSUE TITLE
Some inconsistent naming

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#164]
I know we are running into trouble when naming some class. Could we make it clear once and for all?
## Utility class
- `u-class` or `u-Class` ?
- `r-list` or `r-List` ?
- `t-validate` or `t-Validate` ?

IMO: first answer, u- is a prefix, not a component.
## Grids
- `Column-1` or `Column--1` ?

IMO: second answer, but tricky one. Since `Column` is a `Grid` component, we might have made something like `Grid-c`, `Grid-c--1`.

**Comment by AlexandreBroudin** [comment]
`.u-class`, `r-list`, `t-validate`
`.Grid`, `.Grid-cell`, `Grid-cell--1`

**Comment by ugogo** [comment]
`u-class`, `r-List` because we want to reset a Component, `t-validate`
+1 for `.Grid-cell`, `Grid-cell--1`
