### ISSUE TITLE
Generic UI states

### ISSUE THREAD

**Issue by AlexandreBroudin** [Wisembly/tapestry#168]
Something is missing from most CSS Frameworks, UI States;

Considering 6 UI States;
- Default
- Is Empty
- Is Disabled / Suspended
- Is Loading / Busy
- Is Loaded / Success
- Is Selected

Quite hard to implement in a generic way

**Comment by GabrielCousin** [comment]
Suggestion from @arcanis for disabled sections https://jsfiddle.net/nL1y9gh3/2/

**Comment by GabrielCousin** [comment]
#302
Shipping with `ui-kit-v2`
