### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#175]
We need to test if `filter: blur(0);` is really needed.
It seems to cause issues on Chrome/Linux.

When I disable it, Chrome, Firefox 24 + dev edition and Safari 9 are OK.

**Comment by ugogo** [comment]
Chrome 46.0.2490.86 (64-bit)

### With

![capture d ecran 2015-11-22 a 18 58 48 2](https://s3.amazonaws.com/f.cl.ly/items/111S190t092X0a0N2X2I/Capture%20d%E2%80%99e%CC%81cran%202015-11-22%20a%CC%80%2019.02.02.png)

### Without

![capture d ecran 2015-11-22 a 18 59 55](https://cloud.githubusercontent.com/assets/5040476/11325330/60240076-914b-11e5-8cbf-b657b4392d4d.png)

**Comment by AlexandreBroudin** [comment]
It depends of  your window size;
Non retina MBP El Capitan,  Chrome `49.0.2571.0 canary (64-bit)`

Maximised window:
![capture d ecran 2015-11-23 a 01 16 02](https://cloud.githubusercontent.com/assets/1390084/11327237/067be8a6-9180-11e5-878b-0fd9391ee0b3.png)

Live resized window:
![capture d ecran 2015-11-23 a 01 18 02](https://cloud.githubusercontent.com/assets/1390084/11327242/280a8dec-9180-11e5-892d-a521afae2ada.png)

If I close the modal and reopen in the same size window, no problem.

Without blur(0) I have a better rendering on live window resize, but blury like @ugogo

**Comment by AlexandreBroudin** [comment]
Looks like `transform: translate3d(-50%, -50%, 0);` help
Edit: quite random actualy
