### ISSUE TITLE
Grids | remove .Container

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#209]

**Comment by AlexandreBroudin** [comment]
Why ?

**Comment by GabrielCousin** [comment]
Because it is an extra level of useless nesting

**Comment by AlexandreBroudin** [comment]
But if we want to set a `max-width` ? `.Row` ?

**Comment by GabrielCousin** [comment]
.Grid { max-width: ... } ?

**Comment by AlexandreBroudin** [comment]
Ok , go with `.Grid { max-width: … }` :+1:

**Comment by AlexandreBroudin** [comment]
So, until we don't find a good solution for grid with gutters we should not remove this

**Comment by GabrielCousin** [comment]
I know. Ok with that. I will close this.
