### ISSUE TITLE
Background function

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#219]
- Should we keep it (only used with Pellets)?
- Should we remplace it with new placeholders `%u-primary` / `%u-error` / `%u-info` / `%u-validate`?

**Comment by AlexandreBroudin** [comment]
or we could do this `.Pellet.u-error {}` ?

**Comment by ugogo** [comment]
If new components arrived, they may need those functions?

**Comment by GabrielCousin** [comment]
Then, are you with renaming functions to bg-error / bg-primary / and so on?

**Comment by ugogo** [comment]
Sure!
