### ISSUE TITLE
UI Kit

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#231]
Should we include a Sketch file for each component?
It would be easier to keep it updated this way.
However, IDK how flexible are Sketch symbols (is it possible to change width easily for example?)

**Comment by ugogo** [comment]
100% :+1: 
modules ftw

```
modules/
  button/
    button.scss
    button.md
    button.sketch
```

**Comment by GabrielCousin** [comment]
## Sketch files needed
- [ ] Avatars
- [ ] Badges
- [ ] Box
- [ ] Buttons
- [ ] Dropdowns
- [ ] Inputs
- [ ] List
- [ ] Meter
- [ ] Modal
- [ ] Notification
- [ ] Panel
- [ ] Popovers
- [ ] Switch
- [ ] Table
- [ ] Tabs

**Comment by ugogo** [comment]
Should we close this issue since we won't have .sketch?

**Comment by GabrielCousin** [comment]
![image](https://cloud.githubusercontent.com/assets/7649529/18635853/d43d0092-7e86-11e6-87f9-529a8c19e41e.png)
