### ISSUE TITLE
[Website] Mixed icons

### ISSUE THREAD

**Issue by dcamilleri** [Wisembly/tapestry#236]
Hey guys,

Reporting a small issue but I just spotted that the `linkGoogle` and `linkDropbox` icons are mixed up.

See attached screenshot

![capture d ecran 2016-02-09 a 16 55 43](https://cloud.githubusercontent.com/assets/5601688/12921588/44cff5b4-cf4e-11e5-8c82-e341c9fc4039.png)

**Comment by GabrielCousin** [comment]
Thanks buddy.
