### ISSUE TITLE
Visual tests

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#238]
~~Update backstopJS or give a try to PhantomCSS~~
- [x] Update BackstopJS
- [x] Set up TravisCI to run comparative visual test at each commit
- [x] Update release script to create references

**Comment by GabrielCousin** [comment]
Finally, I am not sure it is a good practice to automatically create new refs when releasing.
It is fine when you are modifying a component. But it is the best way to forget to add new tests since you still have to add a list of selectors to screenshot.

At least, I can add a prompt in the script : "Did you update visual tests? [y/n]"

![image](https://cloud.githubusercontent.com/assets/7649529/13289554/a4e32a0c-db10-11e5-816a-a2133cb4c3a6.png)

**Comment by AlexandreBroudin** [comment]
I agree, tests should be written, not automatic, it should be part of components development.
