### ISSUE TITLE
Refactor modals

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#250]
As discussed with @ugogo, we should try this out:
- `.Modal` is the wrapper (100vh x 100 vw, display: flex, background creating the overlay),
- Use flex to align content, rather than using absolute positionning (should be fix half-pixels issue)
- Make something similar for panels
- Might be better for animations

**Comment by ugogo** [comment]
`.Modal-wrapper` should be the wrapper, with `display: flex` and `position fixed`
