### ISSUE TITLE
Wrong size in input sketch

### ISSUE THREAD

**Issue by AlexandreBroudin** [Wisembly/tapestry#257]
It should be a line-height of 22px not 21px

``` css
$base-vu: 5.5px !default;
$base-lhm: 4 !default;
```

**Comment by GabrielCousin** [comment]
@AlexandreBroudin I checked a few seconds ago (on production server) and it is already 22px.

**Comment by GabrielCousin** [comment]
As discussed with @AlexandreBroudin.
This part is going to be outdated with UI kit update.
We will remove Sketch files for now, until we found a satisfying way to version design assets.
