### ISSUE TITLE
Dropdown-item disabled state

### ISSUE THREAD

**Issue by arcanis** [Wisembly/tapestry#261]
Would be useful to disable some of those two items without completely hiding them:

![image](https://cloud.githubusercontent.com/assets/1037931/14381338/f714d748-fd85-11e5-93db-da7abbd7b143.png)

**Comment by GabrielCousin** [comment]
You're right. But it is a bit fucked-up to disable links since HTML doesn't manage it.

**Comment by arcanis** [comment]
Yep. I currently just set the `disabled` attribute and remove the `href` one, but another (maybe a bit more standard) option is to replace the whole element with a `button[disabled]` when the link should be disabled.

**Comment by GabrielCousin** [comment]
Closing, opening discussion here > https://github.com/Wisembly/tapestry/issues/301
