### ISSUE TITLE
Tabs | Tab and Tab-item

### ISSUE THREAD

**Issue by dcamilleri** [Wisembly/tapestry#309]
Hey there, 

I'm using `.Tabs` items and just realized that on the [documentation](http://tapestry.wisembly.com/components/tabs#bar), the tab item has the `.Tab` class whereas in the build it has the `.Tab-item` class. 

Is that intended ? Can we use both ? 

Thanks

**Comment by GabrielCousin** [comment]
Actually we deployed the future v1 on the server which explains why the documentation doesn't work for you.

We are about to add changes especially on tabs (easier to implement in React). Feel free to have a look and comment on my PR: #296
