### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#310]
Should we add the following code for IE?

```
.Select::-ms-expand {
    display: none;
}
```

**Comment by GabrielCousin** [comment]
![image](https://cloud.githubusercontent.com/assets/7649529/17587998/258082b4-5fcc-11e6-9d8b-7adb26b3285b.png)

**Comment by ugogo** [comment]
Which version of IE?

**Comment by GabrielCousin** [comment]
At least 11. But I haven't checked Edge.

**Comment by GabrielCousin** [comment]
Edge as well
