### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by GabrielCousin** [Wisembly/tapestry#328]
Naming classes is always a pain in the ass, so what about listing some norms or rules to make it easier?

e.g: .Something-button -> .Something-btn

Also, we might want to abbreviate some other words such wrapper, container…

What do ya think?

**Comment by ugogo** [comment]
I don't think a glossary would be the right place to do that, but we can add some lines into the guidelines.

About wrapper and container, idk what we can do to improve that
