### ISSUE TITLE
Dropdown | Add a `is-selected` class

### ISSUE THREAD

**Issue by nicolaschenet** [Wisembly/tapestry#40]
To be able to handle keyboard events on dropdown lists, we should be able to manually set a `.is-selected` class on specific dropdown list items.

Can you add it ASAP as possible guys ? 

![large](https://cloud.githubusercontent.com/assets/1178002/7476448/d54c8ebe-f34d-11e4-9efe-fa8e66b7fe6a.gif)

**Comment by ugogo** [comment]
Done @nicolaschenet 

``` html
<a class="Dropdown-item is-active" ...
```
