### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by ugogo** [Wisembly/tapestry#95]
`.Label` should be in `inline-block` and have a `xs` margin-bottom

**Comment by GabrielCousin** [comment]
Pretty sure that Label--inline exists. Where do we need it?

**Comment by AlexandreBroudin** [comment]
A `label` should be inlined first then, if you need a block, maybe a `.Label--block`

**Comment by ugogo** [comment]
`inline-block` should be there to easily add margin and padding to the `.Label`

**Comment by ugogo** [comment]
0876ae5154db2d26ad2dd7fbc3a1dec91af0a5f9
